core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("movies/",
         views.MovieList.as_view(),
         name="MovieList"),
    path("movie/<int:pk>/",
         views.MovieDetail.as_view(),
         name='MovieDetail'),
    path("movie/<int:movie_id>/vote/", views.CreateVote.as_view(), name="CreateVote"),
    path("movie/<int:movie_id>/vote/<int:pk>/", views.UpdateVote.as_view(), name="UpdateVote"),
    path("", views.MovieList.as_view())
]

smdb/urls.py
from django.contrib import admin
from django.urls import path, include
from core import urls as core_urls
from user import urls as user_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include(user_urls, namespace="user")),
    path("", include(core_urls, namespace="core"))
]

user/urls.py
from django.urls import path
from user import views
from django.contrib.auth import views as auth_views


app_name = "user"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

core/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, "NR - Not rated"),
        (RATED_G, "G - General Audiences"),
        (RATED_PG, "PG - Parental Guidance Suggested"),
        (RATED_R, "R - Restricted")
    )

    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)

    def __str__(self):
        return "{0} ({1})".format(self.title, self.year)

    class Meta:
        ordering = ("-year", "title")


class VoteManager(models.Manager):

    @staticmethod
    def get_vote_or_unsaved_blank_vote(movie, user):
        try:
            return Vote.objects.get(movie=movie,
                                    user=user)
        except Vote.DoesNotExist:
            return Vote(movie=movie,
                        user=user)


class Vote(models.Model):
    UP = 1
    DOWN = -1
    VALUE_CHOICES = ((UP, "UP"), (DOWN, "DOWN"))
    value = models.SmallIntegerField(choices=VALUE_CHOICES)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    voted_on = models.DateTimeField(auto_now=True)

    objects = VoteManager()

    class Meta:
        unique_together = ("user", "movie")

user/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth import get_user_model

from core.models import Vote, Movie


class VoteForm(forms.ModelForm):
    user = forms.ModelChoiceField(widget=forms.HiddenInput,
                                  queryset=get_user_model().objects.all(),
                                  disabled=True)
    movie = forms.ModelChoiceField(widget=forms.HiddenInput,
                                   queryset=Movie.objects.all(),
                                   disabled=True)
    value = forms.ChoiceField(label="Vote",
                              widget=forms.RadioSelect,
                              choices=Vote.VALUE_CHOICES)

    class Meta:
        model = Vote
        fields = ("value", "user", "movie")

core/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from django.shortcuts import redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from .models import Movie, Vote
from .forms import VoteForm


class MovieList(ListView):
    model = Movie
    paginate_by = 10
    paginate_orphans = 3


class MovieDetail(DetailView):
    model = Movie
    queryset = Movie.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        if self.request.user.is_authenticated:
            vote = Vote.objects.get_vote_or_unsaved_blank_vote(
                movie=self.object,
                user=self.request.user
            )
            if vote.id:
                vote_form_url = reverse('core:UpdateVote',
                                        kwargs={'movie_id': vote.movie.id,
                                                'pk': vote.id})
            else:
                vote_form_url = reverse('core:CreateVote',
                                        kwargs={'movie_id': self.object.id})
            vote_form = VoteForm(instance=vote)
            context['vote_form'] = vote_form
            context['vote_form_url'] = vote_form_url
        return context


class CreateVote(LoginRequiredMixin, CreateView):
    form_class = VoteForm

    def get_initial(self):
        initial = super().get_initial()
        initial['user'] = self.request.user.id
        initial['movie'] = self.kwargs['movie_id']
        return initial

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail',
                       kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail',
                                   kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)


class UpdateVote(LoginRequiredMixin, UpdateView):
    form_class = VoteForm
    queryset = Vote.objects.all()

    def get_object(self, queryset=None):
        vote = super().get_object(queryset)
        user = self.request.user

        if vote.user != user:
            raise PermissionDenied('Cannot change another users vote')
        return vote

    def get_success_url(self):
        movie_id = self.object.movie.id
        return reverse('core:MovieDetail', kwargs={'pk': movie_id})

    def render_to_response(self, context, **response_kwargs):
        movie_id = context['object'].id
        movie_detail_url = reverse('core:MovieDetail', kwargs={'pk': movie_id})
        return redirect(to=movie_detail_url)

user/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('core:MovieList')

core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ object.title }} - {{ block.super }}
{% endblock %}

{% block main %}
<h1>{{ object }}</h1>
<p class="lead">
    {{ object.plot }}
</p>
{% endblock %}

{% block sidebar %}
<div>
    {% if vote_form %}
        <form method="post"
              action="{{ vote_form_url }}">
            {% csrf_token %}
            {{ vote_form.as_p }}
            <button
                class="btn  btn-primary">
                Vote
            </button>
        </form>
    {% else %}
    <p>Log in to vote for this movie</p>
    {% endif %}
    This movie is rated:
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
    </span>
</div>
{% endblock %}

core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title %}
All The Movies
{% endblock %}

{% block main %}
    <ul>
        {% for movie in object_list %}
        <li><a href="{% url 'core:MovieDetail' pk=movie.id %}">{{ movie }}</a></li>
        {% empty %}
        <li>
            No movies yet.
        </li>
        {% endfor %}
    </ul>
<p>
    Using https?
    {{ request.is_secure|yesno }}
</p>
{% if is_paginated %}
<nav>
    <ul class="pagination">
        <li class="page-item">
            <a
                href="{% url 'core:MovieList' %}?page=1"
                class="page-link"
            >First
            </a>
        </li>
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a
                href="{% url 'core:MovieList' %}?page={{ page_obj.previous_page_number }}"
                class="page-link">
                {{ page_obj.previous_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="page-item active" >
            <a
                href="{% url 'core:MovieList' %}?page={{ page_obj.number }}"
                class="page-link">{{ page_obj.number }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a
                href="{% url 'core:MovieList' %}?page={{ page_obj.next_page_number }}"
                class="page-link">
                {{ page_obj.next_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a
                href="{% url 'core:MovieList' %}?page=last"
                class="page-link">
                Last
            </a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta
        name="viewpoint"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <title>
        {% block title %}MyMDB{% endblock %}
    </title>
    <style>
        .mymdb-masthead {
        background-color: #EEEEEE;
        margin-bottom: 1em;
        }
    </style>
</head>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">MyMDB</div>
            <a
                class="nav-link"
                href="{% url 'core:MovieList' %}">
                Movies
            </a>
        </nav>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-8 mymdb-main">
            {% block main %}{% endblock %}
        </div>
        <div class="col-sm-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

user/templates/user/register.html
{% extends 'base.html' %}

{% block main %}
<h1>Register for MyMDB</h1>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button
        type="submit"
        class="btn btn-primary">
        Register
    </button>
</form>
{% endblock %}